# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smuckers', '0002_bol_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='agents_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='bill_of_lading',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='car_initial',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bol',
            name='car_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bol',
            name='cosigned_to',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='county_of',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bol',
            name='delivering_carrier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='from_address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='bol',
            name='route',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='shippers_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bol',
            name='state_of',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bolitem',
            name='check_column',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bolitem',
            name='class_or_rate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bol',
            name='shipping_order',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bolitem',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
