# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smuckers', '0004_auto_20170604_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='bol_number',
            field=models.IntegerField(default=0),
        ),
    ]
