# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smuckers', '0005_bol_bol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='truck_approved',
            field=models.BooleanField(default=False),
        ),
    ]
