# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smuckers', '0008_bol_forklift_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bol',
            name='cosigned_to',
            field=models.CharField(blank=True, default='Lineage Logistics', max_length=100),
        ),
        migrations.AlterField(
            model_name='bol',
            name='county_of',
            field=models.CharField(blank=True, default='Ventura', max_length=50),
        ),
        migrations.AlterField(
            model_name='bol',
            name='destination',
            field=models.CharField(blank=True, default='908 E 3rd St, Oxnard', max_length=100),
        ),
        migrations.AlterField(
            model_name='bol',
            name='state_of',
            field=models.CharField(blank=True, default='CA 93030', max_length=20),
        ),
    ]
