# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smuckers', '0010_truckdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='bol',
            name='truck_driver',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='smuckers.TruckDriver'),
        ),
    ]
