# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smuckers', '0012_sentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, default='', max_length=10)),
                ('with_drum', models.IntegerField(default=0)),
                ('without_drum', models.IntegerField(default=0)),
            ],
        ),
    ]
